// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiwTIT_tNi7duv8nh-8hMbstVErhoriAE',
    appId: '1:657117250511:web:e6731feb4292e3908048ba',
    messagingSenderId: '657117250511',
    projectId: 'smart-expense-tracker-2f1af',
    authDomain: 'smart-expense-tracker-2f1af.firebaseapp.com',
    storageBucket: 'smart-expense-tracker-2f1af.firebasestorage.app',
    measurementId: 'G-YSEJ8GBV1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWq7DeQn0yR6Hw7Q-ejirE52ndnexe4rI',
    appId: '1:657117250511:android:111f0f07fc7e931d8048ba',
    messagingSenderId: '657117250511',
    projectId: 'smart-expense-tracker-2f1af',
    storageBucket: 'smart-expense-tracker-2f1af.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtpOLu1WPGRRs8ZeETYCOM9vuGj6VB9xU',
    appId: '1:657117250511:ios:e35d25f66bc2cdbc8048ba',
    messagingSenderId: '657117250511',
    projectId: 'smart-expense-tracker-2f1af',
    storageBucket: 'smart-expense-tracker-2f1af.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseTracker',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtpOLu1WPGRRs8ZeETYCOM9vuGj6VB9xU',
    appId: '1:657117250511:ios:e35d25f66bc2cdbc8048ba',
    messagingSenderId: '657117250511',
    projectId: 'smart-expense-tracker-2f1af',
    storageBucket: 'smart-expense-tracker-2f1af.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiwTIT_tNi7duv8nh-8hMbstVErhoriAE',
    appId: '1:657117250511:web:89c07f34257620098048ba',
    messagingSenderId: '657117250511',
    projectId: 'smart-expense-tracker-2f1af',
    authDomain: 'smart-expense-tracker-2f1af.firebaseapp.com',
    storageBucket: 'smart-expense-tracker-2f1af.firebasestorage.app',
    measurementId: 'G-JW7EMDB1V4',
  );
}
